judge/urls.py
from django.urls import  path
from . import views

app_name = 'judge'
urlpatterns = [
    path('', views.index , name="index"),
    path('problems/' , views.problems , name="problems"),
    path('problem/<int:problem_id>/' , views.problem , name="problem"),
    path('submit/<int:pid>/' , views.submit , name="submit"),
    path('submit/<str:status>/' , views.result , name="result"),
    path('submissions/' , views.submissions , name="submissions"),
    path('register/', views.register_request, name="register"),
    path('login/', views.login_request, name="login"),
    path('logout/', views.log_out, name="logout"),
    path('login/check/', views.login_check, name="login_check"),
    path('register/verify/', views.register_verify, name="register_verify")
]

online_judge/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' ,include('judge.urls') ),
]


templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"> {% endcomment %}
    <link rel="icon" type="image/x-icon" href="https://img.icons8.com/color/48/000000/ruby-programming-language.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% comment %} <link rel="icon" type="image/x-icon" href="https://img.icons8.com/external-inipagistudio-mixed-inipagistudio/64/000000/external-hacker-information-security-inipagistudio-mixed-inipagistudio.png"> {% endcomment %}
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    {% block css %}{% endblock css %}
</head>
<body>
    {% block body %}

    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<section>
    <div class="container-fluid text-light p-4" style="background-color: rgb(0, 16, 110);">
        <div class="text-center">
            <h2>
                ONILNE JUDGE
            </h2>
        </div>
        <div class="row justify-content-center row-cols-3">
            <div class="col-3 text-center p-2">
                <h6 class="border-bottom">About</h6>
                <a href=""></a>
            </div>
            <div class="col-3 text-center p-2">
                <h6 class="border-bottom">Links</h6>
            </div>
            <div class="col-3 text-center p-2">
                <h6 class="border-bottom">Support</h6>
            </div>
        </div>
        <div class="d-flex bd-highlight border-top mb-3 px-3">
            <div class="p-2 bd-highlight"><i class="fa-brands fa-github-square fa-2xl"></i></div>
            <div class="p-2 bd-highlight"><i class="fa-brands fa-linkedin fa-2xl"></i></div>
            <div class="p-2 bd-highlight"><i class="fa-solid fa-at fa-xl"></i></div>
          </div>
    </div>
</section>

templates/index.html
{% extends 'base.html' %}
{% block title %}
Home | OJ
{% endblock title %}
{% block body %}
{% include 'navbar.html' %}
{% if messages %}
{% for message in messages %}
<div{% if message.tags %} class="{{ message.tags }} alert-dismissible fade show text-center" role="alert" {% endif %}>
  {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 mt-3">
      <div class="col mb-4">
        <div class="card">
          <img
            src="https://img.freepik.com/free-photo/futuristic-smart-city-with-5g-global-network-technology_53876-98438.jpg?size=626&ext=jpg&ga=GA1.2.1865860322.1656910696  "
            class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Learn by practice</h5>
            <p class="card-text"></p>
          </div>
        </div>
      </div>
      <div class="col mb-4">
        <div class="card">
          <img
            src="https://img.freepik.com/free-photo/digital-circle-circuit-blue-background-futuristic-technology_53876-124643.jpg?size=626&ext=jpg&ga=GA1.2.1865860322.1656910696"
            class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col mb-4">
        <div class="card">
          <img
            src="https://img.freepik.com/free-photo/3d-render-network-communications-design-background-with-shallow-depth-field_1048-14612.jpg?size=626&ext=jpg&ga=GA1.2.1865860322.1656910696"
            class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
              content.</p>
          </div>
        </div>
      </div>
      <div class="col mb-4">
        <div class="card">
          <img
            src="https://img.freepik.com/free-photo/cool-geometric-triangular-figure-neon-laser-light-great-backgrounds-wallpapers_181624-9331.jpg?size=626&ext=jpg"
            class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
      <div class="col mb-4">
        <div class="card">
          <img
            src="https://img.freepik.com/free-photo/medium-shot-man-wearing-vr-glasses_23-2149126949.jpg?size=626&ext=jpg&ga=GA1.2.1865860322.1656910696"
            class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
              content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% include 'footer.html' %}
  {% endblock body %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
Login | OJ
{% endblock title %}

{% block body %}
{% include 'navbar.html' %}

<section class="vh-100" style="background-color: rgba(255, 223, 149, 0.589);">
    <div class="container py-0 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                
            {% if messages %}
            {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }} alert-dismissible fade show"
                role="alert" {% endif %}>{{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"
                    aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none align-content-center d-md-flex">
                            <img src="https://img.freepik.com/free-vector/secure-login-sign-up-concept-illustration-user-use-secure-login-password-protection-website-social-media-account-vector-flat-style_7737-2270.jpg?size=626&ext=jpg&ga=GA1.2.1865860322.1656910696"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form action="{% url 'judge:login_check' %}" method="post">
                                    {% csrf_token %}
                                    <div class="d-flex align-items-center mb-4 pb-1">
                                        <span class="h1 fw-bold mb-0">Log in</span>
                                    </div>

                                    <h5 class="fw-normal mb-4 pb-3" style="letter-spacing: 1px;">Sign into your account
                                    </h5>

                                    <div class="form-outline mb-4 d-flex flex-row align-items-center">
                                        <i class="fas fa-at fa-lg me-3 fa-fw"></i>
                                        <input type="text" name="username" id="form2Example17" class="form-control form-control-lg" placeholder="Username" required="required"/>
                                    </div>

                                    <div class="form-outline mb-4 d-flex flex-row align-items-center">
                                        <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                                        <input type="password" id="form2Example27" name="password" 
                                            class="form-control form-control-lg" placeholder="Password" required="required"/>
                                    </div>
                                    <div class="pt-1 mb-4 mx-4">
                                        <button class="btn btn-primary btn-lg btn-block  mx-3" type="submit">Login</button>
                                        <a class="small text-muted mx-3" href="#!">Forgot password?</a>
                                    </div>

                                    {% comment %} <a class="small text-muted" href="#!">Forgot password?</a> {% endcomment %}
                                    <p class="mb-4 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'judge:register' %}"
                                            style="color: #2575ff;">Register here</a></p>
                                    <a href="#!" class="small text-muted">Terms of use.</a>
                                    <a href="#!" class="small text-muted">Privacy policy</a>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'judge:index' %}">
            <img src="https://img.icons8.com/nolan/48/ios-photos.png">
            Online Judge
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:problems' %}">Problems</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">About Us</a>
                </li>
            </ul>
            <span class="navbar-text">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'judge:logout' %}">Logout</a>
                  </li>
                  
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:register' %}">Register</a>
                  </li>
                  {% endif %}
                </ul>
              </span>
        </div>
    </div>
</nav>

templates/problem.html
{% extends 'base.html' %}

{% block title %}
{{problem.problem_name | capfirst}}- Submit | OJ
{% endblock title %}
{% block css %}
<style>
    legend {
        max-width: 170px;
    }

    ::selection {
        color: rgb(255, 255, 255);
        background: rgb(58, 150, 255);
    }
</style>
{% endblock css %}

{% block body %}
{% include 'navbar.html' %}
<div class="container-fluid mt-1">
    <div class="container-fluid row">
        <div class="container col-12 col-md-6">
            <h3 class="text-center text-capitalize mt-3">
                {{ problem.problem_name }}
            </h3>
            <p class="mt-3">
                {{problem.problem_desc}}
            </p>
        </div>
        <div class="container col ">
            <form action="{% url 'judge:submit' problem.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="border rounded-lg border-dark p-2">
                    <legend class="fw-bolder fs-3 text-center" style="max-width: 1800px!important;">Submission</legend>
                    <div class="form-group mb-4">
                        <label for="language" class="form-label">Language:</label>
                        <select name="language" class="form-control form-select" id="language" required="required">
                            <option value="">Choose language</option>
                            <option value="c++">C++</option>
                            <option value="java">java</option>
                        </select>
                    </div>
                    <div class="form-group mb-4">
                    <label for="textaera" class="form-label">Write your code here:</label>
                    <textarea name="codeEditor" class="form-control bg-dark text-light" id="textaera"
                        data-toggle="tooltip" data-placement="top" title="Write your code" rows="18"></textarea>
                    </div>
                    <div class="form-group mb-2">
                    <label for="language" class="form-label mt-1">Code file:</label>
                    <input type="file" class="form-control d-inline-block" name="codeFile" style="max-width: 300px;">
                    <input type="submit" class="btn btn-primary mx-md-4" name="submit" value="Submit">
                    </div>
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-danger" role="alert">
                        {{message}}
                      </div>
                      {% endfor %}
                    {% endif %}
                    
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock body %}

templates/problems.html
{% extends 'base.html' %}

{% block title %}
Problems | OJ
{% endblock title %}

{% block body %}
{% include 'navbar.html' %}
{% if request.user.is_authenticated %}
<div class="container p-4">
  <h1 class="text-center">Problems</h1>
  <ol class="list-group list-group-numbered">
    {% if problems %}
    <div class="d-flex justify-content-between list-group-item">
      <div class="fw-bold">Problem name</div>
      <span class="fw-bold">Difficulty</span>
    </div>

    {% for problem in problems %}
    <li class="list-group-item list-group-item-action d-flex justify-content-around align-items-start">
      <div class="ms-2 me-auto">
        <a href="{% url 'judge:problem' problem.id %}" class=" fw-bolder text-decoration-none text-capitalize p-3">
          {{problem.problem_name}}
        </a>
      </div>
      {% if problem.problem_difficulty == 'easy' %}
      <span class="badge rounded-pill bg-success">Easy</span>
      {% endif %}
      {% if problem.problem_difficulty == 'medium' %}
      <span class="badge rounded-pill bg-warning">Medium</span>
      {% endif %}
      {% if problem.problem_difficulty == 'difficult' %}
      <span class="badge rounded-pill bg-danger">Difficult</span>
      {% endif %}
      {% endfor %}
    </li>
  </ol>
  {% else %}
  <div class="alert alert-danger" role="alert">
    Sorry , there are no Problems available.
  </div>
  {% endif %}
</div>
{% else %}
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      Attention !!!
    </div>
    <div class="card-body">
      <h5 class="card-title">Special title treatment</h5>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
    <div class="card-footer text-muted">
      2 days ago
    </div>
  </div>
</div>
{% endif %}

<h2>{{request.user.username}}</h2>
{% endblock body %}

templates/register.html
{% extends "base.html" %}

{% block title %}
Register | OJ
{% endblock title %}

{% block body %}
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'judge:index' %}">
			<img src="https://img.icons8.com/nolan/48/ios-photos.png">
			Online Judge
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'judge:index' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'judge:problems' %}">Problems</a>
				</li>
				<li class="nav-item">
					<a class="nav-link">About Us</a>
				</li>
			</ul>
			<span class="navbar-text">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'judge:login' %}">Login</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" aria-current="page" href="{% url 'judge:logout' %}">Logout</a>
				  </li>
				  <li class="nav-item">
					<a class="nav-link" href="{% url 'judge:register' %}">Register</a>
				  </li>
				</ul>
			  </span>
		</div>
	</div>
</nav>

<section class="vh-100" style="background-color: rgba(255, 223, 149, 0.589);">
	<div class="container h-100">
		<div class="row d-flex justify-content-center align-items-center h-100">
			<div class="col-lg-12 col-xl-11">
				<div class="card text-black" style="border-radius: 25px;">
					<div class="card-body p-md-4">
						<div class="row justify-content-center">
							<div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

								<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4">Sign up</p>

								<form class="mx-1 mx-md-4" action="{% url 'judge:register_verify' %}" method="post">
									{% csrf_token %}
									<div class="d-flex flex-row align-items-center mb-4">
										<i class="fas fa-user fa-lg me-3 fa-fw"></i>
										<div class="form-outline flex-fill mb-0">
											<input type="text" id="form3Example1c" class="form-control" name="firstname"
												placeholder="Firstname" required="required"/>
										</div>
									</div>
									<div class="d-flex flex-row align-items-center mb-4">
										<i class="fas fa-at fa-lg me-3 fa-fw"></i>
										<div class="form-outline flex-fill mb-0">
											<input type="text" id="form3Example1c" class="form-control" name="username"
												placeholder="Username" required="required"/>
										</div>
									</div>

									<div class="d-flex flex-row align-items-center mb-4">
										<i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
										<div class="form-outline flex-fill mb-0">
											<input type="email" id="form3Example3c" class="form-control" name="email"
												placeholder="name@example.com" required="required"/>
										</div>
									</div>

									<div class="d-flex flex-row align-items-center mb-4">
										<i class="fas fa-lock fa-lg me-3 fa-fw"></i>
										<div class="form-outline flex-fill mb-0">
											<input type="password" id="form3Example4c" class="form-control"
												name="password1" placeholder="Password" required="required"/>
										</div>
									</div>
							<div class="d-flex flex-row align-items-center mb-4">
								<i class="fas fa-key fa-lg me-3 fa-fw"></i>
								<div class="form-outline flex-fill mb-0">
									<input type="password" id="form3Example4cd" class="form-control" name="password2"
										placeholder="Re-enter Password" required="required"/>
								</div>
							</div>

							<div class="form-check d-flex mb-2">
								<input class="form-check-input me-2" type="checkbox" value="yes" id="form2Example3c" required="required"/>
								<label class="form-check-label" for="form2Example3">
									I agree all statements in <a href="#!">Terms of service</a>
								</label>
							</div>

							{% if messages %}
									{% for message in messages %}
									<div{% if message.tags %} class="{{ message.tags }} alert-dismissible fade show"
										role="alert" {% endif %}>{{ message }}
										<button type="button" class="btn-close" data-bs-dismiss="alert"
											aria-label="Close"></button>
									</div>
									{% endfor %}
									{% endif %}

							<div class="d-flex justify-content-center mx-3 mb-2 mb-lg-4">
								<button type="submit" class="btn btn-primary btn-lg">Register</button>
							</div>

							</form>

						</div>
						<div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

							<img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
								class="img-fluid" alt="Image">

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>

{% endblock body %}

templates/submissions.html
{% extends 'base.html' %}

{% block title %}Submissions | OJ{% endblock title %}
{% block css %}
 <style>
    body{
        background-color: #ffdf9596;
    }
 </style>
{% endblock css %}
{% block body %}
{% include 'navbar.html' %}
<div class="container">
  <table class="table mt-3">
    <thead class="p-4">
      <tr class="bg-secondary">
        <th scope="col">PROBLEM NAME</th>
        <th scope="col">User</th>
        <th scope="col">VERDICT</th>
        <th scope="col">LANGUAGE</th>
        <th scope="col">TIME</th>
      </tr>
    </thead>
    <tbody>
     

  {% for submission in submissions %}
  {% if submission.verdict == "AC" %}
  <tr style="background-color: #4ce366e0;">
    <th scope="row" class="text-capitalize">{{submission.problem}}</th>
    <td class="text-capitalize">{{submission.user}}</td>
    <td class="text-capitalize">{{submission.verdict}}</td>
    <td class="text-capitalize">{{submission.language}}</td>
    <td class="text-capitalize">{{submission.timestamp}}</td>
  </tr>
  {% elif submission.verdict == "WA"%}
  <tr style="background-color: #ff8463;">
    <th scope="row" class="text-capitalize">{{submission.problem}}</th>
    <td class="text-capitalize">{{submission.user}}</td>
    <td class="text-capitalize">{{submission.verdict}}</td>
    <td class="text-capitalize">{{submission.language}}</td>
    <td class="text-capitalize">{{submission.timestamp}}</td>
  </tr>
  {% endif %}
  
  {% endfor %}
</tbody>
</table>
</div>
{% endblock body %}

templates/submit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Submission- Status | OJ{% endblock title %}
{% block css %}
 <style>
    body{
        background-color: #ffdf9596;
    }
 </style>
{% endblock css %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'judge:index' %}">
            <img src="https://img.icons8.com/nolan/48/ios-photos.png">
            Online Judge
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'judge:problems' %}">Problems</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link">About Us</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="d-flex justify-content-center">
    {% if status == 'wrong_ans' %}
    <div class="card m-4  bg-transparent p-2" style="width: 30rem;">
        <img src="{% static 'images/wrong_ans1.png' %}" class="card-img-top" alt="...">
        <div class="card-body text-center border-top border-warning">
            <h5 class="card-text text-danger fw-bold">You are doing great.<br>
                It worth one more try...</h5>
            <a href="{% url 'judge:problems' %}" class="card-link fw-bold fs-5 btn btn-outline-success px-4 m-3">Retry</a>
            <a href="{% url 'judge:submissions' %}" class="card-link fw-bold fs-5 btn btn-outline-success m-3">Submissions</a>
        </div>
    </div>
    {% elif status == 'correct_ans' %}
    <div class="card m-4 p-2 bg-transparent" style="width: 30rem;">
        <img src="{% static 'images/correct_ans1.png' %}" class="card-img-top" alt="...">
        <div class="card-body text-center border-top border-success mt-2">
            <h5 class="card-text text-success fw-bold">Hurray You are looking great today.<br>
                Keep it up.</h5>
            <a href="{% url 'judge:problems' %}" class="card-link fw-bold fs-5 btn btn-outline-success m-3">Problems</a>
            <a href="{% url 'judge:submissions' %}" class="card-link fw-bold fs-5 btn btn-outline-success m-3">Submissions</a>
        </div>
    </div>
    {% endif %}
</div>

{% endblock body %}